services:
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        volumes:
            - ./:/var/www
            - ./vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - app-network

    php:
        # image: php:8.0-fpm
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: 'laravel'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'tamvu'
            MYSQL_PASSWORD: 'root'
        volumes:
            - ./:/var/www
        ports:
            - 3309:3306
        networks:
            - app-network

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
          - 8080:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_POST: 3306
        networks:
            - app-network
        
    
#Docker Networks
networks:
  app-network:
    driver: bridge
